name: linter

on: [push]
jobs:
  flake8-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.4
      - run: make install
      - run: make build
      - run: make lint
